### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by Nidev-lab** [samuelsantillan/Code-Scape-Hotel-BackEnd#2]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/samuelsantillan/Code-Scape-Hotel-BackEnd/assets/53904695/9314e713-c1a1-4543-8f60-4aaa9c3dc2b6)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by luki1qq** [comment]
Listo
